# Generated by Django 3.2.5 on 2021-07-20 11:12

import core.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('MA', 'Mobile App'), ('W', 'Website'), ('WA', 'Web App'), ('SEO', 'Search Engine Optimisation'), ('DM', 'Digital Marketing'), ('UI', 'Graphic/UI Design'), ('O', 'Other')], max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_files', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=models.SET(core.models.get_sentinel_user), related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
