# Generated by Django 3.2.5 on 2021-07-28 02:43

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='participants',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ManyToManyField(related_name='employee_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=core.models.user_avatar_file_path),
        ),
    ]
