# Generated by Django 3.2.6 on 2021-08-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projecttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ManyToManyField(to='core.ProjectType'),
        ),
    ]
